USE ucode_web;

CREATE TABLE IF NOT EXISTS powers(
    id INT NOT NULL AUTO_INCREMENT,
    hero_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    points INT NOT NULL,
    type ENUM('attack', 'defense') NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS races(
    id INT NOT NULL AUTO_INCREMENT,
    hero_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS teams(
    id INT NOT NULL AUTO_INCREMENT,
    hero_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);